posa_user: root
posa_group: root
posa_shell: /bin/bash

posa_workspace: "/root/workspace"
posa_authorized_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"

ace_tao_version: "8.0.5"
ace_tao_url: "https://download.dre.vanderbilt.edu/ACE%2BTAO-distribution/ACE%2BTAO.tar.gz"

ace_install_root: /opt/ace
ace_link_dir: "{{ ace_install_root }}/ACE_TAO"
ace_wrappers: "{{ ace_link_dir }}"
ace_root: "{{ ace_link_dir }}"
jaws_server_dir: "{{ ace_link_dir }}/apps/JAWS/server"

ace_make_jobs: "2"
ace_debug_build: true

jaws_port: 8080
gdbserver_port: 2345
lldbserver_port: 2346
