---
- name: jaws01 bootstrap + provision
  hosts: jaws
  become: true
  gather_facts: false
  collections:
    - community.general
    - ansible.posix
  roles:
    - bootstrap_python

- name: jaws01 build + scripts
  hosts: jaws
  become: true
  gather_facts: true
  collections:
    - community.general
    - ansible.posix
  roles:
    - common
    - devtools
    - ace_jaws
    - lab_scripts
